"use client";

import { motion, useMotionValue, useTransform, animate, useInView } from "framer-motion";
import { useEffect, useRef } from "react";

const stats = [
  { 
    target: 12500, 
    prefix: "",
    suffix: "+", 
    label: "Active Learners", 
    desc: "Students unlocking their real potential and mastering high-income skills daily." 
  },
  { 
    target: 88.4, 
    prefix: "",
    suffix: "%", 
    label: "Success Rate", 
    desc: "Graduates successfully conquering freelance, corporate, and trading sectors." 
  },
  { 
    target: 45, 
    prefix: "",
    suffix: "+", 
    label: "Skills Unlocked", 
    desc: "Premium, field-tested core modules masterfully completed across the universe." 
  },
  { 
    target: 2.8, 
    prefix: "₹",
    suffix: "Cr+", 
    label: "Student Revenue", 
    desc: "Total collective earnings generated by our students utilizing their true potential." 
  },
];

// ── एनिमेटेड काउंटर कंपोनेंट ──────────────────────────────────────
function Counter({ target, prefix, suffix, isDecimal }: { target: number; prefix: string; suffix: string; isDecimal: boolean }) {
  const count = useMotionValue(0);
  const rounded = useTransform(count, (latest) => {
    if (isDecimal) {
      return `${prefix}${latest.toFixed(1)}${suffix}`;
    }
    return `${prefix}${Math.floor(latest).toLocaleString()}${suffix}`;
  });
  
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { amount: 0.3 });

  useEffect(() => {
    if (inView) {
      const controls = animate(count, target, {
        duration: 1.8,
        ease: [0.16, 1, 0.3, 1],
      });
      return controls.stop;
    } else {
      count.set(0);
    }
  }, [inView, target, count]);

  return <motion.span ref={ref}>{rounded}</motion.span>;
}

// ── नया डिज़ाइनर स्टेट्स कंपोनेंट ───────────────────────────────────
export default function Stats() {
  return (
    <section className="py-20 bg-[#010307] px-4 relative overflow-hidden">
      
      {/* Dynamic Ambient Background Aura */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[200px] bg-gradient-to-r from-cyan-500/5 to-blue-500/5 blur-[140px] rounded-full pointer-events-none" />

      <div className="max-w-6xl mx-auto relative z-10">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, i) => {
            const isDecimal = stat.target % 1 !== 0;

            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -15 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: false, amount: 0.1 }}
                transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1], delay: i * 0.06 }}
                className="relative pl-5 py-4 pr-2 flex flex-col justify-between group transition-all duration-300"
              >
                {/* Minimal Vertical Tech Line Selector (Instead of full boxes) */}
                <div className="absolute left-0 top-0 bottom-0 w-[2px] bg-white/[0.04] group-hover:bg-cyan-500 shadow-[0_0_12px_rgba(34,211,238,0)] group-hover:shadow-[0_0_12px_rgba(34,211,238,0.5)] transition-all duration-300" />
                
                <div>
                  {/* Glowing Indicator Node */}
                  <div className="flex items-center gap-2 mb-1.5 opacity-60 group-hover:opacity-100 transition-opacity duration-300">
                    <span className="text-[9px] font-mono tracking-[0.18em] uppercase text-neutral-400 group-hover:text-cyan-400 transition-colors">
                      // {stat.label}
                    </span>
                  </div>

                  {/* Dynamic Target Metric */}
                  <h3 className="text-3xl lg:text-4xl font-black text-white/90 tracking-tight mb-2 font-mono group-hover:text-white transition-colors">
                    <Counter 
                      target={stat.target} 
                      prefix={stat.prefix} 
                      suffix={stat.suffix} 
                      isDecimal={isDecimal} 
                    />
                  </h3>
                </div>
                
                {/* Context Description */}
                <p className="text-xs text-neutral-500 group-hover:text-neutral-400 leading-relaxed transition-colors duration-300 font-medium max-w-[240px]">
                  {stat.desc}
                </p>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}